=== IBMStreams/OSStreams/src/schema/SPL/Runtime/operatorProfileModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns="http://www.ibm.com/xmlns/prod/streams/spl/operator/profile"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.ibm.com/xmlns/prod/streams/spl/operator/profile"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

<xs:element name="operatorProfile" type="operatorProfileType"/>

<xs:complexType name="operatorProfileType">
  <xs:sequence>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="baseCost" type="bucketDataType"/>
    <xs:element name="inputPort" type="portType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="outputPort" type="portType" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="bucketDataType">
  <xs:sequence>
    <xs:element name="row" type="rowType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="total" type="totalType"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="rowType">
  <xs:attribute name="timestamp" use = "required" type="xs:unsignedLong"/>
  <xs:attribute name="value" use = "required" type="xs:unsignedLong"/>
</xs:complexType>

<xs:complexType name="totalType">
  <xs:sequence>
    <xs:element name="initialTimestamp" type="xs:unsignedLong"/>
    <xs:element name="finalTimestamp" type="xs:unsignedLong"/>
    <xs:element name="min" type="xs:unsignedLong"/>
    <xs:element name="max" type="xs:unsignedLong"/>
    <xs:element name="count" type="xs:unsignedLong"/>
    <xs:element name="sum" type="xs:unsignedLong"/>
    <xs:element name="average" type="xs:double"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="portType">
  <xs:sequence>
    <xs:element name="number" type="bucketDataType"/>
    <xs:element name="size" type="bucketDataType"/>
    <xs:element name="time" type="bucketDataType"/>
  </xs:sequence>
</xs:complexType>

</xs:schema>

=== IBMStreams/OSStreams/src/cpp/SPL/schema/sample/operatorProfileModelSample.xml
<?xml version="1.0" ?>
<operatorProfile
  xmlns="http://www.ibm.com/xmlns/prod/streams/spl/operator/profile"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.ibm.com/xmlns/prod/streams/spl/operator/profile operatorProfileModel.xsd">
  <name>Operator2</name>
  <baseCost>
    <row timestamp="6" value="50"/>
    <row timestamp="8" value="50"/>
    <total>
      <initialTimestamp>10</initialTimestamp>
      <finalTimestamp>12</finalTimestamp>
      <min>100</min>
      <max>345</max>
      <count>560</count>
      <sum>4</sum>
      <average>45.6</average>
    </total>
  </baseCost>
  <inputPort>
    <number>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <row timestamp="8" value="50"/>
      <row timestamp="8" value="50"/>
      <row timestamp="8" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </number>
    <size>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </size>
    <time>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </time>
  </inputPort>
  <outputPort>
    <number>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </number>
    <size>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </size>
    <time>
      <row timestamp="6" value="50"/>
      <row timestamp="8" value="50"/>
      <total>
        <initialTimestamp>10</initialTimestamp>
        <finalTimestamp>12</finalTimestamp>
        <min>100</min>
        <max>345</max>
        <count>2</count>
        <sum>100</sum>
        <average>50</average>
      </total>
    </time>
  </outputPort>
</operatorProfile>
