=== IBMStreams/OSStreams/src/cpp/SPL/FrontEnd/AstNode.xsd
<?xml version="1.0"?>
<xs:schema
  xmlns="http://www.ibm.com/xmlns/prod/streams/spl/AstNodes"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.ibm.com/xmlns/prod/streams/spl/AstNodes"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">

  <!-- Root element containing the model -->
  <xs:element name="AstNodes" type="AstNodesType"/>

  <xs:complexType name="AstNodesType">
    <xs:sequence>
      <xs:element name="AstNode" type="AstNodeType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AstNodeType">
    <xs:sequence>
      <xs:element name="Child" type="ChildType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="tokenType" type="xs:string" use="required"/>
    <xs:attribute name="spelling" type="xs:string" use="optional"/>
    <xs:attribute name="noAstNamespace" type="xs:boolean" use="optional"/>
    <xs:attribute name="start" type="xs:boolean" use="optional"/>
    <xs:attribute name="noStart" type="xs:boolean" use="optional"/>
    <xs:attribute name="text" type="xs:boolean" use="optional"/>
    <xs:attribute name="public" type="xs:boolean" use="optional"/>
    <xs:attribute name="useStartToken" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <xs:complexType name="ChildType">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="repeat" type="xs:boolean" use="optional"/>
    <xs:attribute name="optional" type="xs:boolean" use="optional"/>
  </xs:complexType>

</xs:schema>

=== IBMStreams/OSStreams/src/cpp/SPL/FrontEnd/AstNode.xml
<?xml version="1.0"?>
<AstNodes
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.ibm.com/xmlns/prod/streams/spl/AstNodes AstNode.xsd">

  <AstNode name="opInvokeBody" tokenType="OPINVOKEBODY" noAstNamespace="true"/>
  <AstNode name="portInputs" tokenType="PORTINPUTS" noAstNamespace="true"/>
  <AstNode name="compositeBody" tokenType="COMPOSITEBODY" noAstNamespace="true"/>
  <AstNode name="compositePort" tokenType="COMPOSITEPORT" noAstNamespace="true"/>

  <AstNode name="ampAmpT" tokenType="AMP_AMP" spelling="&amp;&amp;"/>
  <AstNode name="ampEqT" tokenType="AMP_EQ" spelling="&amp;="/>
  <AstNode name="ampT" tokenType="AMP" spelling="&amp;"/>
  <AstNode name="attributeT" tokenType="ATTRIBUTE" spelling="attribute"/>
  <AstNode name="bangT" tokenType="BANG" spelling="!"/>
  <AstNode name="barBarT" tokenType="BAR_BAR" spelling="||"/>
  <AstNode name="barEqT" tokenType="BAR_EQ" spelling="|="/>
  <AstNode name="barT" tokenType="BAR" spelling="|"/>
  <AstNode name="blobT" tokenType="BLOB" spelling="blob"/>
  <AstNode name="booleanT" tokenType="BOOLEAN" spelling="boolean"/>
  <AstNode name="breakT" tokenType="BREAK" spelling="break"/>
  <AstNode name="complex32T" tokenType="COMPLEX32" spelling="complex32"/>
  <AstNode name="complex64T" tokenType="COMPLEX64" spelling="complex64"/>
  <AstNode name="optionalT" tokenType="OPTIONAL" spelling="optional"/>
  <AstNode name="compositeT" tokenType="COMPOSITE" spelling="composite"/>
  <AstNode name="continueT" tokenType="CONTINUE" spelling="continue"/>
  <AstNode name="decimal128T" tokenType="DECIMAL128" spelling="decimal128"/>
  <AstNode name="decimal32T" tokenType="DECIMAL32" spelling="decimal32"/>
  <AstNode name="decimal64T" tokenType="DECIMAL64" spelling="decimal64"/>
  <AstNode name="dotAmpT" tokenType="DOT_AMP" spelling=".&amp;"/>
  <AstNode name="dotBarT" tokenType="DOT_BAR" spelling=".|"/>
  <AstNode name="dotEqEqT" tokenType="DOT_EQ_EQ" spelling=".=="/>
  <AstNode name="dotGeqT" tokenType="DOT_GEQ" spelling=".$gt;="/>
  <AstNode name="dotGreaterT" tokenType="DOT_GREATER" spelling=".&gt;"/>
  <AstNode name="dotHatT" tokenType="DOT_HAT" spelling=".^"/>
  <AstNode name="dotLShiftT" tokenType="DOT_LSHIFT" spelling=".&lt;&lt;"/>
  <AstNode name="dotLeqT" tokenType="DOT_LEQ" spelling=".&lt;="/>
  <AstNode name="dotLessT" tokenType="DOT_LESS" spelling=".&lt;"/>
  <AstNode name="dotMinusT" tokenType="DOT_MINUS" spelling=".-"/>
  <AstNode name="dotModT" tokenType="DOT_MOD" spelling=".%"/>

  <AstNode name="dotNeqT" tokenType="DOT_NEQ" spelling=".!="/>
  <AstNode name="dotPlusT" tokenType="DOT_PLUS" spelling=".+"/>
  <AstNode name="dotRShiftT" tokenType="DOT_RSHIFT" spelling=".&gt;&gt;"/>
  <AstNode name="dotSlashT" tokenType="DOT_SLASH" spelling="./"/>
  <AstNode name="dotStarT" tokenType="DOT_STAR" spelling=".*"/>
  <AstNode name="enumT" tokenType="ENUM" spelling="enum"/>
  <AstNode name="errorT" tokenType="ANTLR3_TOKEN_INVALID" spelling="error" start="false" noStart="true"/>

  <AstNode name="eqEqT" tokenType="EQ_EQ" spelling="=="/>
  <AstNode name="eqT" tokenType="EQ" spelling="="/>
  <AstNode name="expressionT" tokenType="EXPRESSION" spelling="expression"/>
  <AstNode name="falseLiteralT" tokenType="FALSE_LITERAL" spelling="false"/>
  <AstNode name="float32T" tokenType="FLOAT32" spelling="float32"/>
  <AstNode name="float64T" tokenType="FLOAT64" spelling="float64"/>

  <AstNode name="functionT" tokenType="FUNCTION" spelling="function"/>
  <AstNode name="geqT" tokenType="GEQ" spelling="&gt;="/>
  <AstNode name="greaterT" tokenType="GREATER" spelling="&gt;"/>
  <AstNode name="hatEqT" tokenType="HAT_EQ" spelling="^="/>
  <AstNode name="hatT" tokenType="HAT" spelling="^"/>

  <AstNode name="inT" tokenType="IN" spelling="in"/>
  <AstNode name="int16T" tokenType="INT16" spelling="int16"/>
  <AstNode name="int32T" tokenType="INT32" spelling="int32"/>
  <AstNode name="int64T" tokenType="INT64" spelling="int64"/>
  <AstNode name="int8T" tokenType="INT8" spelling="int8"/>

  <AstNode name="lShiftEqT" tokenType="LSHIFT_EQ" spelling="&lt;&lt;="/>
  <AstNode name="lShiftT" tokenType="LSHIFT" spelling="&lt;&lt;"/>
  <AstNode name="leqT" tokenType="LEQ" spelling="&lt;="/>
  <AstNode name="lessT" tokenType="LESS" spelling="&lt;"/>

  <AstNode name="listT" tokenType="LIST" spelling="list"/>
  <AstNode name="mapT" tokenType="MAP" spelling="map"/>
  <AstNode name="minusEqT" tokenType="MINUS_EQ" spelling="-="/>
  <AstNode name="minusMinusT" tokenType="MINUS_MINUS" spelling="--"/>
  <AstNode name="minusT" tokenType="MINUS" spelling="-"/>

  <AstNode name="modEqT" tokenType="MOD_EQ" spelling="%="/>
  <AstNode name="modT" tokenType="MOD" spelling="%"/>
  <AstNode name="mutableT" tokenType="MUTABLE" spelling="mutable"/>
  <AstNode name="neqT" tokenType="NEQ" spelling="!="/>

  <AstNode name="noneT" tokenType="NONE" spelling="none" public="true" start="false" noStart="true"/>
  <AstNode name="operatorT" tokenType="OPERATOR" spelling="operator"/>
  <AstNode name="plusEqT" tokenType="PLUS_EQ" spelling="+="/>
  <AstNode name="plusPlusT" tokenType="PLUS_PLUS" spelling="++"/>
  <AstNode name="plusT" tokenType="PLUS" spelling="+"/>
  <AstNode name="publicT" tokenType="PUBLIC" spelling="public"/>
  <AstNode name="qmarkT" tokenType="QMARK" spelling="?"/>
  <AstNode name="qmarkQmarkT" tokenType="QMARK_QMARK" spelling="??"/>
  <AstNode name="rCurlyT" tokenType="RCURLY" spelling="}"/>
  <AstNode name="rShiftEqT" tokenType="RSHIFT_EQ" spelling="&gt;&gt;="/>
  <AstNode name="pountdT" tokenType="POUND" spelling="#"/>
  <AstNode name="rShiftT" tokenType="RSHIFT" spelling="&gt;&gt;"/>
  <AstNode name="semiT" tokenType="SEMI" spelling=";"/>

  <AstNode name="setT" tokenType="SET" spelling="set"/>
  <AstNode name="slashT" tokenType="SLASH" spelling="/"/>
  <AstNode name="slashEqT" tokenType="SLASH_EQ" spelling="/="/>
  <AstNode name="starT" tokenType="STAR" spelling="*"/>
  <AstNode name="starEqT" tokenType="STAR_EQ" spelling="*="/>
  <AstNode name="statefulT" tokenType="STATEFUL" spelling="stateful"/>
  <AstNode name="staticT" tokenType="STATIC" spelling="static"/>
  <AstNode name="ustringT" tokenType="USTRING" spelling="ustring"/>

  <AstNode name="nullLiteralT" tokenType="NULL_LITERAL" useStartToken="true"/>
  <AstNode name="stringLiteralT" tokenType="STRING_LITERAL" useStartToken="true" text="true"/>

  <AstNode name="tildeT" tokenType="TILDE" spelling="~"/>
  <AstNode name="timestampT" tokenType="TIMESTAMP" spelling="timestamp"/>
  <AstNode name="trueLiteralT" tokenType="TRUE_LITERAL" spelling="true"/>
  <AstNode name="tupleT" tokenType="TUPLE" spelling="tuple"/>
  <AstNode name="typeT" tokenType="TYPE" spelling="type"/>
  <AstNode name="uint8T" tokenType="UINT8" spelling="uint8"/>
  <AstNode name="uint16T" tokenType="UINT16" spelling="uint16"/>
  <AstNode name="uint32T" tokenType="UINT32" spelling="uint32"/>
  <AstNode name="uint64T" tokenType="UINT64" spelling="uint64"/>
  <AstNode name="unaryMinusT" tokenType="UNARY_MINUS" spelling="-"/>
  <AstNode name="useWildcardT" tokenType="USE_WILDCARD" spelling="*"/>
  <AstNode name="voidT" tokenType="VOID" spelling="void"/>
  <AstNode name="floatLiteralT" tokenType="FLOAT_LITERAL" useStartToken="true" text="true"/>
  <AstNode name="intLiteralT" tokenType="INT_LITERAL" useStartToken="true" text="true"/>
  <AstNode name="xmlLiteralT" tokenType="XML_LITERAL" useStartToken="true"/>
  <AstNode name="idT" tokenType="ID" useStartToken="true" text="true"/>
  <AstNode name="hexLiteralT" tokenType="HEX_LITERAL" useStartToken="true" text="true"/>
  <AstNode name="mlCommentT" tokenType="ML_COMMENT" useStartToken="true"/>

  <AstNode name="parenthesizedExpr" tokenType="PARENTHESIZEDEXPR">
    <Child name="expr"/>
  </AstNode>

  <AstNode name="localDecl" tokenType="LOCALDECL">
    <Child name="modifiers"/>
    <Child name="type"/>
    <Child name="localDeclItem" repeat="true"/>
  </AstNode>

  <AstNode name="callExpr" tokenType="CALLEXPR">
    <Child name="target"/>
    <Child name="actual" repeat="true"/>
  </AstNode>

  <AstNode name="compilationUnit" tokenType="COMPILATIONUNIT" noStart="true">
    <Child name="splDoc"/>
    <Child name="splNamespace"/>
    <Child name="useDirectives"/>
    <Child name="definition" repeat="true"/>
  </AstNode>

  <AstNode name="splNamespace" tokenType="SPLNAMESPACE" noStart="true">
    <Child name="splDoc"/>
    <Child name="name" optional="true"/>
  </AstNode>

  <AstNode name="namespaceName" tokenType="NAMESPACENAME">
    <Child name="body"/>
  </AstNode>

  <AstNode name="useDirectives" tokenType="USEDIRECTIVES" noStart="true">
    <Child name="useDirective" repeat="true"/>
  </AstNode>

  <AstNode name="useDirective" tokenType="USE">
    <Child name="namespaceName"/>
    <Child name="useDirectiveTail"/>
  </AstNode>

  <AstNode name="useDirectiveTail" tokenType="USEDIRECTIVETAIL">
    <Child name="idOrStar"/>
  </AstNode>

  <AstNode name="compositeDef" tokenType="COMPOSITEDEF">
    <Child name="compositeHead"/>
    <Child name="compositeBody"/>
    <Child name="end"/>
  </AstNode>

  <AstNode name="compositeHead" tokenType="COMPOSITEHEAD" public="true">
    <Child name="splDoc"/>
    <Child name="annotations"/>
    <Child name="modifiers"/>
    <Child name="compositeT"/>
    <Child name="id"/>
    <Child name="compositeOut"/>
    <Child name="compositeIn"/>
  </AstNode>

  <AstNode name="splDoc" tokenType="SPLDOC" public="true" noStart="true">
    <Child name="comment" optional="true"/>
  </AstNode>

  <AstNode name="compositeIn" tokenType="COMPOSITEIN" public="true">
    <Child name="compositePort" repeat="true"/>
  </AstNode>

  <AstNode name="compositeOut" tokenType="COMPOSITEOUT" public="true">
    <Child name="compositePort" repeat="true"/>
  </AstNode>

  <AstNode name="formalClause" tokenType="FORMALCLAUSE" spelling="param">
    <Child name="compositeFormal" repeat="true"/>
  </AstNode>

  <AstNode name="typeClause" tokenType="TYPECLAUSE" spelling="type" noStart="true">
