=== IBMStreams/OSStreams/src/schema/SPL/Core/enumerationModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ibm.com/xmlns/prod/streams/spl/enumeration"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ibm.com/xmlns/prod/streams/spl/enumeration"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

   <xs:element name="enumerationModel" type="enumerationModelType"/>

   <xs:complexType name="enumerationModelType">
      <xs:sequence>
         <xs:element name="class" type="xs:token"/>
         <xs:element name="enumerators" type="enumeratorsType"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="enumeratorsType">
      <xs:sequence>
         <xs:element name="enumerator" type="enumeratorType" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>

   <xs:complexType name="enumeratorType">
      <xs:sequence>
         <xs:element name="name" type="xs:token"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== IBMStreams/OSStreams/src/cpp/SPL/schema/sample/enumerationModelSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<enumerationModel xmlns="http://www.ibm.com/xmlns/prod/streams/spl/enumeration"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.ibm.com/xmlns/prod/streams/spl/enumerator enumerationModel.xsd">

   <class>LogLevel</class>

   <enumerators>
      <enumerator>
         <name>error</name>
      </enumerator>

      <enumerator>
         <name>info</name>
      </enumerator>

      <enumerator>
         <name>debug</name>
      </enumerator>

      <enumerator>
         <name>trace</name>
      </enumerator>
   </enumerators>

</enumerationModel>
